baseURL = 'https://andrewwelch.net/'
languageCode = 'en-us'
title = 'Andrew Welch'
theme = 'paper'
sectionPagesMenu = 'menu'

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
[[menu.main]]
  name = "Mastodon"
  url = "https://social.andrewwelch.net/@fortera"
  weight = 10